name: dev_pull_closed
# this will run for both on merge closed  with success and
# unmerged closed pr with failure
# not good if you are trying to conserve action cycles

on:
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo $GITHUB_WORKFLOW Action has fired successfully!

