name: dev_pull_closed

on:
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo $GITHUB_WORKFLOW Action has fired successfully!

